version: '2'
# Our services (containers)
services:
    nginx:
        hostname: docker-nginx
        container_name: docker-nginx
        image: nginx:latest
        ports:
            - "8080:80"
            - "1443:443"
        # Mount directories - host_dir:container_dir
        volumes:
            - ./containers/nginx:/etc/nginx/conf.d
            - ./www:/var/www
            - ./logs:/var/log/nginx
        links:
            - php
    php:
        hostname: docker-php
        container_name: docker-php
        build: ./containers/php
        working_dir: /var/www/hello.dev
        links:
            - mysql
            - redis
        volumes:
            - ./www:/var/www
            - ./containers/php/my.ini:/usr/local/etc/php/conf.d/my.ini
    mysql:
        hostname: docker-mysql
        container_name: docker-mysql
        image: mysql:8
        ports:
            - "13306:3306"
        volumes:
            - ./containers/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: hellodb
    redis:
        hostname: docker-redis
        container_name: docker-redis
        image: redis:alpine
        volumes:
            - ./containers/redis:/data